name: Release Subfolder

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "GitHub Actions Bot"

      - name: Extract Commit Message
        id: extract_tag
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Commit message: $COMMIT_MSG"

          if [[ $COMMIT_MSG =~ release-(v[0-9]+\.[0-9]+\.[0-9]+) ]]; then
            TAG="${BASH_REMATCH[1]}"
            echo "Extracted tag: $TAG"
            echo "TAG_NAME=$TAG" >> $GITHUB_ENV
          else
            echo "No valid release tag found in commit message. Skipping release."
            exit 1
          fi

      - name: Extract Subfolder and Push Branch
        run: |
          git subtree split --prefix=Assets/com.edia.uxf -b subfolder-branch
          git push -f origin subfolder-branch

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "$TAG_NAME" --title "Release $TAG_NAME" --target subfolder-branch
